---
title: "Presidential Inauguration Speeches"
output: html_document
---

# Part 0: Install and load libraries
```{r, message=FALSE, warning=FALSE}
packages.used=c("tm", "dplyr", "tidytext", "ggplot2", "topicmodels")

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE)
}

# load packages
library(tm)
library(dplyr)
library(tidytext)
library(topicmodels)
library(ggplot2)
source("../lib/TextProcessing.R")
```

# Part 1: Most-used words
We first examine the most frequently used words in presidential inauguration speeches. Below is the code to process all speeches and plot the most frequently used words across all speeches.
```{r, message=FALSE, warning=FALSE}
folder.path="../data/InauguralSpeeches/"
docs <- getSpeeches(folder.path)

# get most frequent words
tdm <- TermDocumentMatrix(docs)
freq <- sort(rowSums(as.matrix(tdm)), decreasing=TRUE)
wf <- data.frame(word=names(freq), freq=freq)
wf$word <- factor(wf$word, levels = wf$word[order(wf$freq, decreasing=TRUE)])

# build histogram 
p <- ggplot(subset(wf, freq>=head(freq, 25)[[25]]), aes(x=word, y=freq))
p <- p + geom_bar(stat="identity", fill="red", colour="darkgreen")   
p <- p + theme(axis.text.x=element_text(angle=45, hjust=1))
p
```

Some comments here

# Part 2: Topic modeling
```{r, message=FALSE, warning=FALSE}
folder.path="../data/InauguralSpeeches/"
# empiricially removing words that does not convey info in these termsspeeches
extra.words <- c("will", "can", "may", "upon", "let", "must", "shall", 
                 "every", "one", "now", "today", "time", "day", "new", 
                 "united", "states", "country", "nation")
docs <- getSpeeches(folder.path, extra.words)
dtm <- DocumentTermMatrix(docs)
lda <- LDA(dtm, k=4, 
           method="Gibbs", 
           control=list(nstart=4, seed=list(272, 166, 966, 377), delta=0.1,
                        best=TRUE, burnin=0, iter=2000, thin=2000))
topics <- as.matrix(topics(lda))
terms <- as.matrix(terms(lda, 12))
```

